# Generated by Django 5.0.1 on 2024-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusesAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusName', models.CharField(max_length=100)),
                ('BusArrivalTime', models.DateTimeField()),
                ('BusArrivalDate', models.DateTimeField()),
            ],
        ),
    ]
