# Generated by Django 5.0.1 on 2024-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0003_member_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='busesavailable',
            name='Amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busesavailable',
            name='BusDestination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busesavailable',
            name='From',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
