# Generated by Django 5.0.1 on 2024-01-31 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0004_busesavailable_amount_busesavailable_busdestination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafariLinkApp.member')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafariLinkApp.busesavailable')),
            ],
        ),
    ]
