# Generated by Django 5.0.1 on 2024-01-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0009_remove_member_is_active_remove_member_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_permissions',
        ),
    ]
