# Generated by Django 4.2.6 on 2024-02-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0011_member_groups_member_is_active_member_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='NuberOfSeats',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
