# Generated by Django 4.2.6 on 2024-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0012_member_nuberofseats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='NuberOfSeats',
            new_name='SeatNumber',
        ),
        migrations.AddField(
            model_name='busesavailable',
            name='NuberOfSeats',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
