# Generated by Django 4.2.6 on 2024-02-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0013_rename_nuberofseats_member_seatnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='SeatNumber',
            new_name='amount_paid',
        ),
    ]
