# Generated by Django 4.2.6 on 2024-02-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0014_rename_seatnumber_member_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
