# Generated by Django 4.2.6 on 2024-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0015_member_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='seatNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
