# Generated by Django 4.2.6 on 2024-02-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0016_member_seatnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
