# Generated by Django 4.2.6 on 2024-02-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0017_member_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busesavailable',
            old_name='BusName',
            new_name='BusNumberPlate',
        ),
    ]
