# Generated by Django 4.2.6 on 2024-02-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0018_rename_busname_busesavailable_busnumberplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busesavailable',
            old_name='BusNumberPlate',
            new_name='BusName',
        ),
    ]
