# Generated by Django 4.2.6 on 2024-02-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0019_rename_busnumberplate_busesavailable_busname'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusName', models.CharField(max_length=100)),
                ('From', models.CharField(blank=True, max_length=100, null=True)),
                ('BusDestination', models.CharField(max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
