# Generated by Django 4.2.6 on 2024-02-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0020_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='generalNotification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
