# Generated by Django 4.2.6 on 2024-02-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0021_notifications_generalnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=50)),
                ('CheckoutRequestID', models.CharField(max_length=50)),
                ('ResultCode', models.CharField(max_length=10)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MpesaReceiptNumber', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=15)),
            ],
        ),
    ]
