# Generated by Django 4.2.6 on 2024-02-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0022_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='busesavailable',
            name='TransactionCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
