# Generated by Django 4.2.6 on 2024-02-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0023_busesavailable_transactioncode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busesavailable',
            name='TransactionCode',
        ),
        migrations.AddField(
            model_name='member',
            name='TransactionCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
