# Generated by Django 4.2.6 on 2024-02-24 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0024_remove_busesavailable_transactioncode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='TransactionCode',
        ),
    ]
