# Generated by Django 4.2.6 on 2024-02-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafariLinkApp', '0025_remove_member_transactioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='BusDestination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='BusName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
